print("Vou pedir-lhe dois números.")
x = eval(input("Escreva o primeiro número, x = "))
y = eval(input("Escreva o segundo número, y = "))
z = (x + 3 * y) * (x - y)
print ("O valor de (x + 3 * y) * (x - y) é: ", z)